title: Merna Hossam
# logo: /assets/img/headshot_circle.png
Hey there! I'm Merna Hossam, a recent grad from the Faculty of Computer and Data Science at Alexandria University.
I'm super pumped about diving headfirst into the exciting world of data science! My thing is uncovering those hidden gems in data,
you know, the kind of insights that can actually solve real-world problems and make a difference. Let's make data magic happen! 🚀💡
show_downloads: true
theme: jekyll-theme-minimal
